name: Deploy Laravel & Vue to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/id_rsa bitnami@${{ secrets.EC2_HOST }} "echo SSH Connection Successful!"

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa bitnami@${{ secrets.EC2_HOST }} << 'EOF'
          sudo rm -rf /opt/bitnami/apache/htdocs/*
          cd /opt/bitnami/apache/htdocs
          git clone ${{ secrets.REPO_URL }} .
          composer install --no-dev --optimize-autoloader
          npm install && npm run build
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          sudo chown -R bitnami:daemon /opt/bitnami/apache/htdocs
          sudo chmod -R 775 /opt/bitnami/apache/htdocs/storage /opt/bitnami/apache/htdocs/bootstrap/cache
          sudo systemctl restart apache2
        
